C  Error status values for IONSYS system
C
C     < error description >
C         INTEGER  <error name>
C         PARAMETER ( <error name> = -40nn )

C     Illegal ionospheric correction type.
          INTEGER         ILL_ION
          PARAMETER     ( ILL_ION = -4001 )

C     No visibility data for the current operation.
          INTEGER         NO_VISDATA
          PARAMETER     ( NO_VISDATA = -4002 )
