C     *****************************************************************
C
C     /mrao/post/include/mapsys_save.inc
C
C     Common include file for MAPSYS library - contains map redtape
C     common block (dumped during map redtape editing routines)
C
C     *****************************************************************
C
      integer             mapsys_save(512)
      common  / msyssav / mapsys_save
