
* Include file defining offset observations (Ryle Telescope)
* (value of OFFSET in TRACK-Q-ITEM) - from ryle.(tel)5km-devices:incl

* last update 28 June 2004 from RT version 28 June 2004

      integer*2    o_5point, o_raster, o_7point, o_const,
     #             o_scan, o_hex, o_m5point,
     #             o_19point, o_37point, o_61point

      parameter   (o_5point  = 1)
      parameter   (o_raster  = 2)
      parameter   (o_7point  = 3)
      parameter   (o_const   = 4)
      parameter   (o_scan    = 5)
      parameter   (o_hex     = 6)
      parameter   (o_m5point = 7)
      parameter   (o_19point = 8)
      parameter   (o_37point = 9)
      parameter   (o_61point = 10)

