C Physical Telescope Integer Codes
C ================================
C
C CLFST (151MHz and 38MHz)
       integer      clfst
       parameter   (clfst = 1)

C Ryle (all frequencies)
       integer      five_km
       parameter   (five_km = 2)

C Ryle (all frequencies)
       integer      ryle
       parameter   (ryle = 2)

C Mobile VLBI
       integer      vlbi_81p5MHz
       parameter   (vlbi_81p5MHz = 3)
